unicorn/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

unicorn/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

unicorn/questions/urls.py
from django.conf.urls import url
from . import views

app_name = 'questions'

urlpatterns = [
	# ex: /questions/
	url(r'^$',
		views.IndexView.as_view(),
		name='index'),

	# ex: /questions/5/
	url(r'^(?P<pk>[0-9]+)/$',
		views.DetailView.as_view(),
		name='detail'),

	# ex: /questions/5/results/
	url(r'^(?P<pk>[0-9]+)/results/$',
		views.ResultsView.as_view(),
		name='results'),

	# ex: /questions/5/vote/
	url(r'^(?P<question_id>[0-9]+)/vote/$',
		views.vote,
		name='vote'),
]

unicorn/unicorn/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^login/', include('login.urls')),
	url(r'^questions/', include('questions.urls')),
	url(r'^events/', include('events.urls')),
    url(r'^admin/', admin.site.urls),
]

unicorn/events/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

unicorn/login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

unicorn/questions/models.py
from __future__ import unicode_literals

import datetime
from django.utils import timezone
from django.db import models


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	user_name = models.CharField(max_length=20)
	pub_date = models.DateTimeField('date published')
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.question_text

	# Not sure if we need it. Probably not
	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	text = models.CharField(max_length=200)
	user_name = models.CharField(max_length=20)
	pub_date = models.DateTimeField('date published')
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.text

unicorn/events/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return HttpResponse("Hello, world! This is the Events page")

unicorn/login/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return HttpResponse("Hello, world! This is the Login page")

unicorn/questions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Question, Answer


class IndexView(generic.ListView):
	template_name = 'questions/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions."""
		return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'questions/detail.html'


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'questions/results.html'


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_answer = question.answer_set.get(pk=request.POST['answer'])
	except (KeyError, Answer.DoesNotExist):
		# Redisplay the question voting form
		return render(request, 'questions/detail.html', {
			'question': question,
			'error_message': "You didn't select an answer",
		})
	else:
		selected_answer.votes += 1
		selected_answer.save()
		return HttpResponseRedirect(reverse('questions:results',
			args=(question.id,)))

# def index(request):
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	context = {
# 		'latest_question_list': latest_question_list,
# 	}
# 	return render(request, 'questions/index.html', context)

# def detail(request, question_id):
# 	try:
# 		question = Question.objects.get(pk=question_id)
# 	except Question.DoesNotExist:
# 		raise Http404("Question does not exist")

# 	context = {
# 		'question': question,
# 		'answers': Answer.objects.filter(question=question),
# 	}
# 	return render(request, 'questions/detail.html', context)

# def results(request, question_id):
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'questions/results.html', {'question': question})

unicorn/questions/templates/questions/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'questions:vote' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
	<input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
	<label for="answer{{ forloop.counter }}">{{ answer.text }}</label><br/>
{% endfor %}
<input type="submit" value="Vote" />
</form>

<!-- <pre>Question text: {{ question.question_text }}
User name: {{ question.user_name }}
Publication date: {{ question.pub_date }}
Votes: {{ question.votes }}
Number of answers: {{ answers|length }}</pre>

<ul>
{% for answer in question.answer_set.all %}
	<li>{{ answer.text }}</li>
{% endfor %}
</ul> -->

unicorn/questions/templates/questions/index.html
<textarea id="newQuestion" rows="5" cols="80"></textarea>
<button onClick="postNewQuestion()">Post</button>

{% if latest_question_list %}
	{% for question in latest_question_list %}
		<div class="question" id="question{{ forloop.counter }}">
			<a href="{% url 'questions:detail' question.id %}">
			{{ question.question_text }}</a></div>
	{% endfor %}
{% else %}
	<p>No questions are available</p>
{% endif %}

<script>
function postNewQuestion() {
	alert("Question: "
		+ document.getElementById('newQuestion').value);
}
</script>

<!-- TODO: Avoid race condition -->
<!-- https://docs.djangoproject.com/en/1.9/ref/models/expressions/#avoiding-race-conditions-using-f -->

unicorn/questions/templates/questions/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for answer in question.answer_set.all %}
	<li>{{answer.text }} -- {{ answer.votes }} vote{{answer.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'questions:detail' question.id %}">Vote again?</a>